spring:
  datasource:
#    database connection configuration
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytestdb
    username: shawnhxf
    password: shui8016

  #Statitcs and SQL logs
  jpa:

    show-sql: true   #show sql query command in console
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
    generate-ddl: true   #generate ddl automatically based on class
    hibernate:
      ddl-auto: update  #update the database when the code is update.

